name: xiaomi
version: 1.0.0+1
publish_to: none
description: 小米商城
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  get: 4.6.5
  dio: ^5.2.1
  flutter_swiper_view: ^1.1.8
  shared_preferences:
  crypto:
  flutter_staggered_grid_view: ^0.6.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: xiaomi
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: userIcon
      fonts:
        - asset: assets/fonts/userIconfont.ttf
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/2.0x/xiaomiBanner.png
    - assets/images/3.0x/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/2.0x/xiaomiBanner2.png
    - assets/images/3.0x/xiaomiBanner2.png
    - assets/images/hot_search.png
    - assets/images/2.0x/hot_search.png
    - assets/images/3.0x/hot_search.png
    - assets/images/service.png
    - assets/images/2.0x/service.png
    - assets/images/3.0x/service.png
    - assets/images/user.png
    - assets/images/2.0x/user.png
    - assets/images/3.0x/user.png
    - assets/images/user_ad1.png
    - assets/images/2.0x/user_ad1.png
    - assets/images/3.0x/user_ad1.png
    - assets/images/user_ad2.png
    - assets/images/2.0x/user_ad2.png
    - assets/images/3.0x/user_ad2.png
    - assets/images/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png




