name: xiaomi
version: 1.0.0+1
publish_to: none
description: 小米商城
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  get: 4.6.5
  dio: ^5.2.1
  flutter_swiper_view: ^1.1.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: xiaomi
      fonts:
        - asset: assets/fonts/iconfont.ttf



